# Generated by Django 4.2.4 on 2023-08-28 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_image_alter_article_last_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subtext',
            field=models.CharField(default='A subtitle should go here. It should not exceed 108 characters.', max_length=108),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='last_edited',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 28, 2, 22, 9, 373578)),
        ),
    ]
